# -*- coding: utf-8 -*-
"""YOLOv5 VisDrone training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12UwaKVNfwzxR5DVGDuuQzoDBr4hqSudV
"""

import torch
import torchvision
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
torch.cuda.is_available()
torch.cuda.empty_cache()

!git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5

from google.colab import drive
drive.mount('/content/drive')

!unzip level_1_test.zip



!pip install -r requirements.txt

import os
from random import choice
import shutil
os.environ['KMP_DUPLICATE_LIB_OK']='True'

"""# Model trainning in GPU"""

with tf.device('/GPU:0'):
    !python train.py --img 4911 --batch 1 --epochs 5 --data C:\Users\USER\yolov5\VisDroneDETreproducefull.v1i.yolov5pytorch\data.yaml --weights yolov5s.pt

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir runs

with tf.device('/GPU:0'):
    !python detect.py --source runs\train\exp30\b.jpg --weights runs\train\200epoch\weights\best.pt



